### ISSUE TITLE
Error: "Missing Tag Prefix"

### ISSUE THREAD

**Issue by ejohnlove** [middlebury/moodle-mod_adaptivequiz#20]
Installed version the adaptive quiz plugin version "2013022800" under Moodle version 2.5.2+ (Build: 20130913)

Whenever I start an attempt on an Adaptive Quiz, I get the following error:

Missing tag prefix
More information about this error
Debug info: 
Error code: missingtagprefix
Stack trace:
line 476 of /lib/setuplib.php: moodle_exception thrown
line 412 of /mod/adaptivequiz/fetchquestion.class.php: call to print_error()
line 238 of /mod/adaptivequiz/fetchquestion.class.php: call to fetchquestion->retrieve_tags_with_question_count()
line 266 of /mod/adaptivequiz/fetchquestion.class.php: call to fetchquestion->initalize_tags_with_quest_count()
line 358 of /mod/adaptivequiz/adaptiveattempt.class.php: call to fetchquestion->fetch_questions()
line 337 of /mod/adaptivequiz/adaptiveattempt.class.php: call to adaptiveattempt->get_question_ready()
line 209 of /mod/adaptivequiz/attempt.php: call to adaptiveattempt->start_attempt()

**Comment by adamfranco** [comment]
Hi @ejohnlove , The error message being printed isn't especially helpful, but the problem is that the adaptive quiz isn't finding any questions tagged with levels.

For example, if you are using a question-difficulty scale of 1-10, then you will need to tag questions in your question bank with their difficulty using the tags, 'adpq_1', 'adpq_2', ..., 'adpq_10'. The adaptive quiz works best with large banks of questions spanning most of the difficulty-levels in your defined range, but it will pick the next-best match if some levels don't have questions.

A forthcoming update will replace the error message with one that is more informative, but really you just need to add difficulty-level tags to the questions.

Best,
Adam
