### ISSUE TITLE
Adaptive Quiz Images Missing moodle  2.9

### ISSUE THREAD

**Issue by nip231** [middlebury/moodle-mod_adaptivequiz#31]
Images in the questions in the Question bank when previewed show OK
Running through the Adaptive Quiz with the questions the images show a red cross and a blank space
I set up a standard Moodle Quiz and images work in that fine on all Browsers.
Probably  bug in the Adaptive Quiz code which we thought would be a possibility due to it being out of date.

**Comment by adamfranco** [comment]
Thanks for this report. It will be a little while before I'm able to investigate this due to other projects. Patches are always welcome if you have a chance to look into it before I do.

**Comment by dheuring** [comment]
I've experienced this problem of inserting/embedding image and audio files via the text editor.  The images appear fine and the audio works perfectly when editing quiz questions.  But when one actually takes the test the images are missing and when one clicks on the audio player, it vanishes.  It does seem to be a problem with adaptive quiz not finding the correct path for the image/audio file.  Bug # 28 reported here also seems to be the same problem.

I posted this issue on the associated Moodle forum about a year ago because I thought maybe it was something I was doing wrong with the settings.  In researching it again today, I see it was previously tagged as issue 31 and 28 here on github.  I'm not a developer so there's no way I can help with a patch.  Is it possible to work on a solution sooner rather than later?  This is an awesome plugin and, apart from the image/media problem, it works really well.  Much appreciated.

**Comment by dheuring** [comment]
Dear Adam,

I'm in a bit of a fix.  We need to add listening questions to the adaptive test.  But as a stated above, the audio player displays but when you click to start it, it vanishes.  Images also don't appear.  I went ahead and replicated the issue reported in # 28 and believe it is the same problem I am experiencing.  The only difference is I got the image to appear by increasing the folder number +2 (...question/questiontext/535/1/508/... replaced by ...question/questiontext/537/1/508/...).  I've attached two images to show how the image appeared when I changed the folder number.  It seems to be that the wrong folder is being accessed.  I wish I could fix this myself but I'm not a developer.

I've read through the other bugs reported here and it appears that your development team has higher priorities than fixing bugs for this plugin.  As I said, I'm in a tight spot here since we have an impending deadline to launch the listening component for this test.  I would really like your help in getting the images to display and audio player to work.  Let me know what it will take to devote some time to this.  

Thank you very much!!!

David

![Uploading Untitled.png…]()
![Uploading Untitled1.jpg…]()

**Comment by adamfranco** [comment]
Hi @nip231, @dheuring. This issue should now be resolve in the 1.2.2 release.

Moodle requires modules using the Question API to impliment a `<module>_question_pluginfile()` method to make access checks and load the file contents. This was missing from mod_adaptivequiz.
