### ISSUE TITLE
Error reading from database - after choosing "View report"

### ISSUE THREAD

**Issue by nouza** [middlebury/moodle-mod_adaptivequiz#37]
Adaptive quizes work with levels well, but when a student finish a test, there is an error of database, and the test starts again! "Question Analysis" shows right statistics, but "View report" shows "Error reading from database".
Pls - where is a problem? (Moodle 2.5)

**Comment by adamfranco** [comment]
Hi @nouza , unfortunately I'm not able to replicate the issue myself and without more information don't know where to start looking. Please include the PHP errors from your sever logs or temporarily turn on **Display debug messages** under
- Site Administration
  - Development
    - Debuggging

and copy-paste the PHP error text so that we know where the error is occurring. 

Also, what are the exact versions of Moodle and the Plugin you are running?

**Comment by thdebay** [comment]
Hello,

I encountered the same issue. Here is the debugging message.

I submitted a PR that seemingly fixes the issue

```
Debug info: Table 'moodle.mdl_adaptivequiz_attempt' doesn't exist
(...)
```
