### ISSUE TITLE
Quiz Navigation

### ISSUE THREAD

**Issue by sameeraswal** [middlebury/moodle-mod_adaptivequiz#40]
Hi,
Is there any way to have "Quiz navigation" option in adaptive quiz also, just like we have in case of normal quiz?
If not then it can be added as enhancement.

**Comment by adamfranco** [comment]
Hi @sameeraswal , are you referring to the block Quizes put in the menu like this?
![screen shot 2016-04-28 at 12 25 58 pm](https://cloud.githubusercontent.com/assets/25242/14893229/84d45d72-0d3c-11e6-8ddb-5e2ea0be57a6.png)

What is your goal in having such a menu? The adaptive quiz can't really be navigated like normal quizzes since questions can't be skipped and returned to and aren't a defined sequence.

**Comment by sameeraswal** [comment]
Hi @adamfranco 
Thanks for reply. I agree with you regarding the questions can't be skipped.
So we just want to have the timer "**Time left 0:59:42**" so that user can see remaining time during the quiz.

**Comment by adamfranco** [comment]
Having the timer displayed seems like a reasonable feature. :+1: We'd be happy to review a Pull Request if you (or others) put one together but we have many other projects higher in our own priority list currently and wouldn't likely get around to implementing this ourselves for some time.

**Comment by Khalidkabchi** [comment]
Hello everyone,
I hope you are all doing well!
Let me first introduce myself: my name is Khalid KABCHI, Moroccan and I am preparing a thesis about adaptive testing (specifically in physics).
I plan to create an adaptive test but I find huge difficulties in this sense.
For that can you help me to create my own adaptive test?

**Comment by adamfranco** [comment]
Thank you for submitting this issue. This repository is now archived: The sponsor of this plugin, Middlebury College, is no longer using Moodle. Development is continuing on other forks of the project. See https://moodle.org/plugins/mod_adaptivequiz for more information and latest releases.
