### ISSUE TITLE
Images still not loading!

### ISSUE THREAD

**Issue by saadsm** [middlebury/moodle-mod_adaptivequiz#42]
Hello there.

First of all, its a brilliant plugin - Been using since a year and the staff loves it. Using Moodle 2.9, i am still having problem with quiz images being fetched from Question Bank? The version report said it had been fixed, so i uninstalled plugin completely, and reinstalled and made a new quiz - Still the problem resides... We are using workarounds to attach images from a source outside Moodle to be able to work, but our new question bank has images uploaded through file manager. Attached screenshots.

![screen shot 2017-01-12 at 2 02 20 pm](https://cloud.githubusercontent.com/assets/1969307/21885614/3f6675b2-d8da-11e6-9eea-d521d06c3c75.png)

![screen shot 2017-01-12 at 2 01 45 pm](https://cloud.githubusercontent.com/assets/1969307/21885618/41cc9fca-d8da-11e6-87a2-c2c251eea797.png)

**Comment by adamfranco** [comment]
Thanks for kind words @saadsm! 

4fe647aba19a4f78496eb6babc9b254558266fa7 fixed an issue (reported in #31 and #28) that was totally preventing images from loading correctly in all cases (including new Moodle installations). 

Your report in this issue and @dheuring's comments on #31 indicate that the 4fe647aba19a4f78496eb6babc9b254558266fa7 fix didn't resolve all image-loading issues in some already-existing Moodle installations, though it did for new Moodle installations. My hunch is that there is something going on in some existing Moodle installations that is changing file URLs in a way that they don't change in a fresh installation. Maybe it is caused by a plugin folks are enabling or maybe there are internal file and file-usage ids that normally increment in parallel, but aren't guaranteed to.

Unfortunately I'm not able to replicate this issue on my own installation of Moodle. Additionally my institution is moving away from Moodle and while I'm happy to review patches & [Pull Requests](https://help.github.com/articles/about-pull-requests/), I'm not able devote significant time to tracking down issues in this module. If you or others in the community are able to track down the cause of the issue (or even better provide a fix), I'd be happy to put in in place and package a new release.

**Comment by adamfranco** [comment]
The `MOODLE_31` branch now includes a patch #55  from @semteacher that makes changes to image access. Please test the new code and report if it fixes your issue.

**Comment by dheuring** [comment]
I tested this latest version of adaptivequiz on my development server Moodle 3.4+.  Unfortunately, it has not resolved the image-loading problem I've had for quite some time now.  Same problem as reported above where the image shows when editing, but not when running the test.  I've used the same work-around as saadsm by placing my images and audio files in a directory outside of Moodle and linking to them.  Life goes on....

**Comment by Andmat7** [comment]
The bug is on the line 694 from file lib.php , The course module is being obtained with the course id instead of a course module id, I temporarily solved the bug commented the lines 694 to 697 and 704 to 718  from lib.php

**Comment by adamfranco** [comment]
Thanks for that tip, @Andmat7. If you or anyone else is able to provide a PR with a full fix, that would be great.

**Comment by semteacher** [comment]
I have investigated an issue that @Andmat7 found. As I understand he is right - there is no correct coursemodule instance info there. As I compared to conventional quiz - they get $cm only from attempt.
However -  there is no such method in this module. 
So, I decide to retrieve all necessary fields directly using existing info. And got some success. Images now have been loaded for me... Notice: was lack of testing - I have had not enough ADPQ  quizzes instances (Actually, I do this job "just for fun" - I am no longer involved in project were ADPQ module was used). 
I have opened pull request with this fix.

**Comment by adamfranco** [comment]
Thank you for submitting this issue. This repository is now archived: The sponsor of this plugin, Middlebury College, is no longer using Moodle. Development is continuing on other forks of the project. See https://moodle.org/plugins/mod_adaptivequiz for more information and latest releases.
